### ISSUE TITLE
Exception with text/plain

### ISSUE THREAD

**Issue by sgsweb** [nlmarco/svndumptransformer#2]
Exception in thread "main" java.io.IOException: Unexpected mime-type: text/plain
        at co.codewizards.svndumptransformer.SvnDumpTransformer.transformTextContent(SvnDumpTransformer.java:218)
        at co.codewizards.svndumptransformer.SvnDumpTransformer.transform(SvnDumpTransformer.java:137)
        at co.codewizards.svndumptransformer.SvnDumpTransformer.main(SvnDumpTransformer.java:67)

**Comment by iqbal1979** [comment]
Even I have encountered the IOException issue:

Exception in thread "main" java.io.IOException: Unexpected mime-type: application/x-gzip
        at co.codewizards.svndumptransformer.SvnDumpTransformer.transformTextContent(SvnDumpTransformer.java:218)
        at co.codewizards.svndumptransformer.SvnDumpTransformer.transform(SvnDumpTransformer.java:137)
        at co.codewizards.svndumptransformer.SvnDumpTransformer.main(SvnDumpTransformer.java:67)
